# Generated by Django 6.0.1 on 2026-01-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birt_date',
            new_name='birth_date',
        ),
    ]
