# Generated by Django 6.0.1 on 2026-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_birt_date_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
